// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection
open System.Runtime.InteropServices

[<assembly: AssemblyTitleAttribute("Irc.FSharp")>]
[<assembly: AssemblyProductAttribute("Irc.FSharp")>]
[<assembly: AssemblyDescriptionAttribute("An IRC client library for F#.")>]
[<assembly: AssemblyVersionAttribute("0.1.1")>]
[<assembly: AssemblyFileVersionAttribute("0.1.1")>]
[<assembly: GuidAttribute("694ab3b0-8929-4f78-ab72-55f29eb48a36")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "Irc.FSharp"
    let [<Literal>] AssemblyProduct = "Irc.FSharp"
    let [<Literal>] AssemblyDescription = "An IRC client library for F#."
    let [<Literal>] AssemblyVersion = "0.1.1"
    let [<Literal>] AssemblyFileVersion = "0.1.1"
    let [<Literal>] Guid = "694ab3b0-8929-4f78-ab72-55f29eb48a36"
