// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection
open System.Runtime.InteropServices

[<assembly: AssemblyTitleAttribute("Irc.FSharp.Tests")>]
[<assembly: AssemblyProductAttribute("Irc.FSharp")>]
[<assembly: AssemblyDescriptionAttribute("Unit tests for Irc.FSharp.")>]
[<assembly: AssemblyVersionAttribute("0.0.2")>]
[<assembly: AssemblyFileVersionAttribute("0.0.2")>]
[<assembly: GuidAttribute("c38c2af6-4ebe-4bfa-bb28-18f6f10324e0")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "Irc.FSharp.Tests"
    let [<Literal>] AssemblyProduct = "Irc.FSharp"
    let [<Literal>] AssemblyDescription = "Unit tests for Irc.FSharp."
    let [<Literal>] AssemblyVersion = "0.0.2"
    let [<Literal>] AssemblyFileVersion = "0.0.2"
    let [<Literal>] Guid = "c38c2af6-4ebe-4bfa-bb28-18f6f10324e0"
